name: THEJB.AI
author: JB
description: "AI 논문 리뷰와 구현"

url: "https://the-jb.github.io/pages-theme"

img_baseurl: "https://img.thejb.ai"
link_icons:
  -
    icon: /github.svg
    url: https://github.com/the-jb
  -
    icon: /scholar.svg
    url: https://scholar.google.com/citations?user=SQYbgngAAAAJ

permalink: /:title/

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    # line_numbers: true
    default_lang: python
    guess_lang: true

sass:
  style: :compressed

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
