name: THEJB.AI
author: JB
description: "AI 논문 리뷰와 구현"

url: "https://the-jb.github.io/pages-theme"

img_baseurl: "https://img.thejb.ai"
link_icons:
  -
    icon: github-icon
    url: https://github.com/the-jb
  - 
    icon: profile-icon
    url: https://thejb.ai
  - 
    icon: blog-icon
    url: https://blog.thejb.ai
  -
    icon: scholar-icon
    url: https://scholar.google.com/citations?user=SQYbgngAAAAJ

permalink: /:title/

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    # line_numbers: true
    default_lang: python
    guess_lang: true

sass:
  style: :compressed

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

giscus:
  src: "https://giscus.app/client.js"
  data_repo: ""
  data_repo_id: ""
  data_category: ""
  data_category_id: ""
  data_mapping: "og:title"
  data_reactions_enabled: "0"
  data_emit_metadata: "0"
  data_theme: "light"
  crossorigin: "anonymous"
